module.exports = {
  chain: [
    "polygon",
    "mantle",
    "opbnb",
    "linea",
    "bsc",
    "arbitrum",
    "avax",
    "klay",
    "cronos",
    "wemix",
    "combo",
    "kcs",
  ],
  rpc: {
    polygon: "https://1rpc.io/matic",
    arbitrum: "https://1rpc.io/arb",
    kcs: "https://go.getblock.io/897277680f784c8f9371ec0421b2261b",
    avax: "https://1rpc.io/avax/c",
    klay: "https://1rpc.io/klay",
    bsc: "https://1rpc.io/bnb",
    wemix: "https://api.wemix.com",
    cronos: "https://1rpc.io/cro",
    mantle: "https://1rpc.io/mantle",
    linea: "https://1rpc.io/linea",
    opbnb: "https://1rpc.io/opbnb",
    combo: "https://rpc.combonetwork.io",
    tron: "https://trx.mytokenpocket.vip",
  },
};
